### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by bstein-clever** [njpanderson/Citrus#1]
I was curious what the status here was. It says it's in development, but it doesn't look like there have been any changes for several months.

I was hoping to be able to use this as a replacement for [Varnish Purge](https://github.com/aelvan/VarnishPurge-Craft).

Thanks!

**Comment by njpanderson** [comment]
Hi there @bstein-clever - Thanks for your interest but unfortunately I've decided not to continue with this as I have too many other commitments. I'll take this repo down in a couple of days to avoid further confusion - Feel free to fork it first if you want to use the existing code (such as it is) in any way!

**Comment by bstein-clever** [comment]
Well, I'd love to at least understand what kind of state it's in - which pieces are done and which need more work - before you do that.

I personally don't mind a deprecated repo that others can work off of/contribute to, but it's just not immediately apparent from a quick glance that that's the state of things.

In the end, though, your call.

**Comment by njpanderson** [comment]
Honestly, it's not a lot - mainly setting up the barebones Craft 3 plugin interface. The code which actually interacts with Varnish is sound for the Craft 2 version, but it would need work to function correctly in 3.

Sorry I can't be more help!

**Comment by njpanderson** [comment]
Looks like you're in luck, possibly, @bstein-clever — my work _did_ in fact make an MIT released version of Citrus for Craft 3. Check it out here:
https://github.com/Whitespacers/Citrus

Likely comes with no warranty but feel free to give it a go and see if it works for you?
